version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-server
    ports:
      - "8081:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
